# Generated by Django 3.2.6 on 2021-08-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='No title', max_length=255),
        ),
    ]
